In [4]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [20]:
arr[0][1]

2

In [23]:
arr[0, 1]

2

In [25]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])